name: CICD
on:
  push:
    branches:
      - main
    paths: 
     - '**/*.html'
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: check code
        run: echo "Checkout the code from repo"
  test:
    runs-on: ubuntu-latest
    needs: code
    steps:
      - name: test
        run: echo "Test the code"
  build:
    runs-on: ubuntu-latest
    needs: 
      - code
      - test
    steps:
      - name: build
        run: echo "Docker build"
  push:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: push
        run: echo "Push to the docker hub"
  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: deploy
        run: echo "deployed on the production"
