name: Hello

on:
  workflow_dispatch: 
    inputs:
      enviroments:
        description: this is enviroment value where workflow will run
        type: choice
        options:
          - dev
          - prd
          - stg

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say wish
        run: echo "Hello rahul kaise how"
      - name: okay by by
        run: echo "Thanky ramesh"
  okby:
    runs-on: ubuntu-latest
    steps:
      - name: kal miloge
        run: echo "rahul kal miloge na?"
  seeyou:
    runs-on: ubuntu-latest
    needs: 
      - greet 
    
    steps:
      - name: tata
        run: echo "tata rahul"
