name: Talking to someone
on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say wish
        run: echo "Hello rahul kaise how"
      - name: okay by by
        run: echo "Thanky ramesh"
  okby:
    runs-on: ubuntu-latest
    steps:
      - name: kal miloge
        run: echo "rahul kal miloge na?"
